# config.py
"""
Contains all static configuration data, such as CAN IDs, register maps,
and physical motor parameters.
"""
# --- CAN Bus Configuration ---
CAN_INTERFACE = 'socketcan'
CAN_CHANNEL = 'can0'
CAN_BITRATE = 500000

# --- CAN IDs ---
CAN_ID_COMMAND_BASE = 0x000
CAN_ID_TELEMETRY_BASE = 0x200
CAN_ID_TELEMETRY_EXTRA_BASE = 0x280
CAN_ID_RESPONSE_BASE = 0x300
CAN_ID_SCAN_BROADCAST = 0x700

# --- Official SimpleFOC Register Map ---
REG_STATUS = 0x00
REG_TARGET = 0x01
REG_ENABLE = 0x04
REG_CONTROL_MODE = 0x05
REG_TORQUE_MODE = 0x06
REG_MODULATION_MODE = 0x07

REG_ANGLE = 0x09
REG_VELOCITY = 0x11

REG_TELEMETRY_REG = 0x1A
REG_TELEMETRY_CTRL = 0x1B
REG_TELEMETRY_DOWNSAMPLE = 0x1C

REG_VOLTAGE_Q = 0x20
REG_VOLTAGE_D = 0x21
REG_CURRENT_Q = 0x22
REG_CURRENT_D = 0x23

REG_VEL_PID_P = 0x30
REG_VEL_PID_I = 0x31
REG_VEL_PID_D = 0x32
REG_VEL_PID_LIM = 0x33
REG_VEL_PID_RAMP = 0x34
REG_VEL_LPF_T = 0x35
REG_ANG_PID_P = 0x36
REG_ANG_PID_I = 0x37
REG_ANG_PID_D = 0x38
REG_ANG_PID_LIM = 0x39
REG_ANG_PID_RAMP = 0x3A
REG_ANG_LPF_T = 0x3B

REG_CURQ_PID_P = 0x40
REG_CURQ_PID_I = 0x41
REG_CURQ_PID_D = 0x42
REG_CURQ_LPF_T = 0x45
REG_CURD_PID_P = 0x46
REG_CURD_PID_I = 0x47
REG_CURD_PID_D = 0x48
REG_CURD_LPF_T = 0x4B

REG_VOLTAGE_LIMIT = 0x50
REG_CURRENT_LIMIT = 0x51
REG_VELOCITY_LIMIT = 0x52
REG_DRIVER_VOLTAGE_PSU = 0x55
REG_VOLTAGE_SENSOR_ALIGN = 0x56

REG_POLE_PAIRS = 0x63
REG_PHASE_RESISTANCE = 0x64
REG_KV = 0x65
REG_INDUCTANCE = 0x66

REG_MOTOR_ADDRESS = 0x7F

# --- Custom Registers (Mapped to a private range) ---
REG_CUSTOM_SAVE_TO_EEPROM    = 0xE1
REG_CUSTOM_FLIP_SENSOR_DIR   = 0xE2
REG_CUSTOM_TELEMETRY_PERIOD  = 0xE3

# Deprecated/Internal - for reference
REG_MOTION_MODE_TORQUE = 0 # Used internally by tuners